### ISSUE TITLE
alignment issues

### ISSUE THREAD

**Issue by paulwilman** [weather34/Meteobridge-Beta#1]
Brian,

Seeing a few alignment issues with the latest smart betat as can be seen from www.paulwilman.com/pw

1) clock top module - text is too big
2) Dark sky forecast - UV forecast is half missing
3) Footer - too narrow
4) Davis forecast top module (far right) - the (R) after Davis is too high
5) annual temperature top module - average not reporting, and there are a couple of "--" that I suspect should be text

Paul

**Comment by weather34** [comment]
you always see alignment issues :-) but i dont see what you see unfortunately ..dont or I wouldnt use ideas from existing or older templates everything will be totally different. 

there is no option for clock in position 1 so i dont know how you got that
unfortunately darksky will be dropped will only use wu darksky has always be way of the forecast
mark here and probably is for others outside the popular GFS zone.GFS is literally diabolical for Istanbul this last winter highlighted that quite strongly . 
footer designed to cater an array of screen sizes and only needs minimal text .
there is no registered r in the davis personal insert ?
annual temperature fine here it will actually become current monthly average ..recent API changes ??

screenshot below of what i work on locally . note it does not support any browsers pre 2019

this is a long term project and will not be ready until december 2019 at the earliest there is a lot of new modules to build and additional options it will be a tedious slow process .it is definitely not
ready in anyway to be used as a reliable template and I build my own meteobridge API locally to test ideas . working example is at https://weather34.com 

![beta](https://user-images.githubusercontent.com/20555738/59159132-df40b780-8acd-11e9-8520-a4db362663f4.png)

**Comment by paulwilman** [comment]
Brian,

I hope you are ok. 

I do see to always see alignment issues!

Totally recognise it is a long term beta....love testing things so thought I would give it a quick try, running in background. Issue was me copying over my settings1.php!!!! It obviously tried to create the time/date module that doesn’t exist anymore! It also created a few other issues that I have now sorted in www.paulwilman.com/pw

The footer still seems to be too narrow and average temperature not coming through, even though I updated to latest nano forward today?

Please let me know if you need any testing.

Paul

**Comment by weather34** [comment]
thanks but it is a long way off before i commit myself to it with a fine toothpick..

**Comment by paulwilman** [comment]
Brian,

Ready whenever....

Paul

**Comment by weather34** [comment]
ok well it is important to follow the updates i.e livedata.php just now otherwise if you raise an issue it may not be apparent  due to either changes or recent fix etc
