### ISSUE TITLE
Addition add-on ?

### ISSUE THREAD

**Issue by meteolive57290** [weather34/Meteobridge-Beta#2]
hello
I just "test" the template version
it works nickel
http://seremange-meteolive.franceserv.com/pws/index.php
add additional module for users of the German network "Lufdaten": https://luftdaten.info/
and sensors in service ?
Congratulations for this version I am very ready
Regards
fto meteolive57290

**Comment by weather34** [comment]
no problem if service provides a json ? API ? or if you have a file with data stored ?

**Comment by meteolive57290** [comment]
+1 yep @ Brian
Luftdaten.info
Link to the doc: 
https://github.com/opendata-stuttgart/meta/wiki/APIs

Query command:
http://api.luftdaten.info/v1/sensor/**ID**
the query returns sensor data for the last 5 minutes for a specific sensor **ID**
23127 for example for my sensor
Thnx for collaboration and good day 
Regards
fto meteolive57290

**Comment by weather34** [comment]
ok will take a look sometime in the future shouldnt be too difficult.

**Comment by meteolive57290** [comment]
i remain confident 200% :) thank you good luck Best

**Comment by weather34** [comment]
ok based on your station ID and API I compiled this ,im not sure which are the valid values as there are numerous in the API .but this uses the last P1 Value .im sure it can be refined but need more users to use this type of Air quality monitor to determine the various outputs.

* important these are required the files updated ...
easyweathersetup.php
index.php
luftdaten.php
airqualityluftdaten.php
aqiluftdateninfo.php
stationcron.php
jsondata folder has demo file 

![luftdw](https://user-images.githubusercontent.com/20555738/59210251-da573300-8bb5-11e9-9b80-abd9a1744a04.jpg)

**Comment by meteolive57290** [comment]
hello @Brian super responsive
ok i just made uoplad for the new module "Lufdaten"
at home it does not work properly! the datas do not return with the ID. from my station ?!
my "easyweathersetup.php" file ok up to date ...
same problem with the identifiers of my other two sensors 
an idea ?
thank you in advance 👍 
Regards
fto meteolive57290

![Capture](https://user-images.githubusercontent.com/51605896/59251772-e5987600-8c2a-11e9-8c2f-81f3090f0fff.PNG)

![Capture1](https://user-images.githubusercontent.com/51605896/59251796-ef21de00-8c2a-11e9-868a-e9a0de08cbcd.PNG)

![Capture2](https://user-images.githubusercontent.com/51605896/59251807-f517bf00-8c2a-11e9-8d1c-14a2efcc60f3.PNG)

**Comment by weather34** [comment]
hi im not getting to involved in this at this stage .. did you replace all files listed . including stationcron.php etc .. it is working fine here .. can we leave this till a later date ...brian

**Comment by weather34** [comment]
i used the id you provided yesterday

**Comment by weather34** [comment]
http://api.luftdaten.info/v1/sensor/23127/

**Comment by weather34** [comment]
replace stationcron.php in mbdbfiles should fix the blank repsonse .. requires a backslash after station id..should find something like this in the jsondata/luftdaten.txt file 

`[{"location":{"id":11733,"exact_location":0,"altitude":"205.7","country":"FR","longitude":"6.092","indoor":0,"latitude":"49.316"},"id":3892195526,"sampling_rate":null,"sensor":{"sensor_type":{"id":14,"manufacturer":"Nova Fitness","name":"SDS011"},"id":23127,"pin":"1"},"sensordatavalues":[{"value_type":"P1","id":8250880734,"value":"5.83"},{"value_type":"P2","id":8250880735,"value":"3.27"}],"timestamp":"2019-06-11 08:03:08"},{"location":{"id":11733,"exact_location":0,"altitude":"205.7","country":"FR","longitude":"6.092","indoor":0,"latitude":"49.316"},"id":3892212473,"sampling_rate":null,"sensor":{"sensor_type":{"id":14,"manufacturer":"Nova Fitness","name":"SDS011"},"id":23127,"pin":"1"},"sensordatavalues":[{"value_type":"P1","id":8250916468,"value":"7.62"},{"value_type":"P2","id":8250916470,"value":"3.80"}],"timestamp":"2019-06-11 08:05:39"}]`

**Comment by weather34** [comment]
should end up with this for Air Quality

![endup](https://user-images.githubusercontent.com/20555738/59255207-55622d00-8c3a-11e9-9848-f4cbb7ba269b.png)

**Comment by meteolive57290** [comment]
hmm okay i had downloaded the files listed ...
after verification, actually the jsondata/ luftdaten.txt file was empty! 
it's finally ok thanks for the solution 🥇 Regards fto

**Comment by meteolive57290** [comment]
edit _ not anymore

**Comment by weather34** [comment]
looks ok now ... have a good day...brian
