### ISSUE TITLE
no update for forcast wu, ds,....

### ISSUE THREAD

**Issue by palafran** [weather34/Meteobridge-Beta#3]
Hi,
I use this Weather Template since 2 Years
today I made the first update this Year, 18.6.19
the problem I see, no update for airquality, earthquake, nearby metar, forcast wu, ds, current conditions.
I see that the Folder of Jonsdata are empty

**Comment by weather34** [comment]
no url not possible to help much but perhaps check if meteobridge is setup to run stationcron correctly

**Comment by palafran** [comment]
my URL
http://www.wetter-gern.com/pws/
![mb_setting](https://user-images.githubusercontent.com/51994057/59793569-2baea300-92d7-11e9-9358-ca0d3e9ce5df.PNG)
no AQI, Earthquake, nearby metar offline,...

**Comment by weather34** [comment]
something wrong in meteobridge settings your 
http://www.wetter-gern.com/pws/mbridge/MBrealtimeupload.txt

is full of blank values --  

`19/06/2019 21:30:30 -- -- -- -- -- -- -- -- -- -- -- m/s C hPa mm -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 4.0 13019 -- CARAMBOLA2 -- -- [rain0total-sum24h] -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 91846 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 29 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 5 94.0 16:04 22:49 06:41 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- [rain0total-max@M1] [rain0total-max@Y1] -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- _`

**Comment by palafran** [comment]
yes, since the last update, the RF module is defective

**Comment by palafran** [comment]
but that has nothing to do with the AQI or Earthquake update ?

**Comment by weather34** [comment]
unfortunately it does because the mysql script does not function therefore the forecast etc scripts wont run because there is no data to execute for mysql in the first part of stationcron.php

**Comment by weather34** [comment]
http://www.wetter-gern.com/pws/mbdbfiles/stationcron.php

returns **Couldn't fetch records**

**Comment by weather34** [comment]
closed meteobridge hardware issue...
