### ISSUE TITLE
Download version Beta 

### ISSUE THREAD

**Issue by meteolive57290** [weather34/Meteobridge-Beta#4]
hello 
I just downloaded the beta version for my second station
http://seremange-meteolive.franceserv.com/pws/index.php

it seems to work fine except for me:
module "forecast" and annexes "daily" / "summary"
"current conditions" module> offline data and metar station (ELLX) not up to date
module "purple air" > offline and "lufdaten" not updated either ......

in comparison, the normal version works:
http://valdefench57sgz.franceserv.com/pws/index.php?lang=en

Best regards
fto

**Comment by weather34** [comment]
are you running stationcron.php , i just did it manually and forecast etc appeared on your site

**Comment by weather34** [comment]
still need stationcron.php to run every 30 minutes ...
