### ISSUE TITLE
Missing tag in dark CSS

### ISSUE THREAD

**Issue by steepleian** [weather34/Meteobridge-Beta#7]
This section of code missing from weather34dashboard.dark.css: -

.darkskyiconcurrent{position:relative;margin-top:10px;margin-bottom:-5px;margin-left:35px;float:left}.darkskyiconcurrent span1{font-size:.9em}heatindex{margin-top:-25px;display:block;font-size:.7rem}

Causing module box to overflow when currentconditionsds.php set in dark mode.

**Comment by weather34** [comment]
Hi Ian i wouldn't convert this to Weewx for use its a long slow process of finalising each file which will be marked Final, at present you will see finalize and all dark sky options will be eventually removed . this version is primed for NANOSD and Davis hardware so some of the averages and  charts may not work for weewx ? best stick with Williams version for reliability and better chance of being  workable with weewx ? eta December 2019.

**Comment by steepleian** [comment]
Ok Brian. I just wanted to flag it up to you. Not planning to substitute
the regular WeeWX for this for general, just looking at it as an academic
exercise but it does play with WeeWX very nicely. Was interested in your
treatment of the charts, very interesting. I am playing around with
Highcharts at the moment (see my site). Get many requests for charts of all
types so thought would make it easy for myself. From one piece of html
currently can generate approx 40 different charts. WeeWX-api generates json
data which is used with chart html page url + parameters. Still work in
progress.
Take care,
Ian

**Comment by weather34** [comment]
no problem ian absolutely zero experience of weewx on my part . charts reap the feature of periodically calling a file via meteobridge services..
